-- Migration from v0.5.0 to v0.6.0
-- Generated: 2025-11-26 16:00:40
-- 
-- This migration was automatically generated by comparing db.sql between tags.
-- Please review and test before applying to production.

-- ==== UPGRADE ====
-- Upgrade from v0.5.0 to v0.6.0

-- Create new table: Ingredient_Types
CREATE TABLE Ingredient_Types (
    type_id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT
);

-- Add type_id column
ALTER TABLE Ingredients ADD COLUMN type_id INT AFTER gluten_status;
ALTER TABLE Ingredients ADD CONSTRAINT fk_ingredient_type 
    FOREIGN KEY (type_id) REFERENCES Ingredient_Types(type_id) ON DELETE SET NULL;

-- Add weight column
ALTER TABLE Ingredients ADD COLUMN weight DECIMAL(10, 2) AFTER default_unit_id;

-- Rename unit 'Item' to 'Each'
UPDATE Units SET name = 'Each', abbreviation = 'ea' WHERE name = 'Item' AND category = 'Item';
-- Rename unit 'Slice' to 'Cube'
UPDATE Units SET name = 'Cube', abbreviation = 'cube' WHERE name = 'Slice' AND category = 'Item';

-- ==== DOWNGRADE ====

-- Rename unit 'Cube' back to 'Slice'
UPDATE Units SET name = 'Slice', abbreviation = 'slice' WHERE name = 'Cube' AND category = 'Item';
-- Rename unit 'Each' back to 'Item'
UPDATE Units SET name = 'Item', abbreviation = 'item' WHERE name = 'Each' AND category = 'Item';

-- Remove weight column
ALTER TABLE Ingredients DROP COLUMN weight;

-- Remove type_id column
ALTER TABLE Ingredients DROP CONSTRAINT fk_ingredient_type;
ALTER TABLE Ingredients DROP COLUMN type_id;

-- Drop table: Ingredient_Types
DROP TABLE IF EXISTS Ingredient_Types;
