# GitHub Actions CI/CD Pipeline for Recipes Application
#
# This workflow:
# - Runs tests on every push and PR
# - Automatically deploys to production when a release tag is created
#
# Setup Instructions:
# 1. Copy this file to .github/workflows/deploy.yml in your repository
# 2. Add these secrets to your GitHub repository settings:
#    - DEPLOY_SSH_KEY: Private SSH key for deployment user
#    - DEPLOY_HOST: Production server hostname
#    - DEPLOY_USER: Deployment user (e.g., 'recipes')
#    - DEPLOY_PATH: Installation path (e.g., '/opt/recipes')
#
# Usage:
# - Push to main branch: Runs tests only
# - Create release tag (v1.2.3): Runs tests and deploys to production

name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ main ]

jobs:
  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: testpassword
          MYSQL_DATABASE: recipes_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: backend/requirements.txt
      
      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt
      
      - name: Initialize test database
        env:
          DATABASE_URL: mysql+pymysql://root:testpassword@127.0.0.1:3306/recipes_test
        run: |
          mysql -h 127.0.0.1 -u root -ptestpassword recipes_test < db/db.sql
          cd backend
          python manage_migrations.py init
      
      - name: Run backend tests
        env:
          DATABASE_URL: mysql+pymysql://root:testpassword@127.0.0.1:3306/recipes_test
        run: |
          cd backend
          # Add your test command here
          # python -m pytest tests/
          python -c "from app import app; print('✓ Backend import successful')"
  
  test-frontend:
    name: Test Frontend
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      - name: Install dependencies
        run: |
          cd frontend
          npm ci
      
      - name: Build frontend
        run: |
          cd frontend
          npm run build
      
      - name: Run frontend tests
        run: |
          cd frontend
          # Add your test command here
          # npm test
          echo "✓ Frontend build successful"
  
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [test-backend, test-frontend]
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts
      
      - name: Deploy to production
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
          VERSION: ${{ steps.get_version.outputs.VERSION }}
        run: |
          ssh -i ~/.ssh/deploy_key $DEPLOY_USER@$DEPLOY_HOST << 'EOF'
            set -e
            cd $DEPLOY_PATH
            
            # Store current version for rollback
            CURRENT_VERSION=$(git describe --tags --always 2>/dev/null || echo "unknown")
            echo "Current version: $CURRENT_VERSION"
            
            # Fetch and checkout new version
            git fetch --all --tags
            git checkout $VERSION
            
            # Backend deployment
            cd backend
            source .venv/bin/activate
            pip install -q -r requirements.txt
            
            # Apply migrations
            python manage_migrations.py upgrade
            
            # Restart backend
            sudo systemctl restart recipes-backend
            
            # Check if service started successfully
            sleep 2
            if ! sudo systemctl is-active --quiet recipes-backend; then
              echo "ERROR: Backend service failed to start"
              echo "Rolling back to $CURRENT_VERSION"
              git checkout $CURRENT_VERSION
              sudo systemctl restart recipes-backend
              exit 1
            fi
            
            # Frontend deployment
            cd ../frontend
            npm ci --silent
            npm run build
            
            echo "✓ Deployment successful: $VERSION"
          EOF
      
      - name: Notify deployment success
        if: success()
        run: |
          echo "✓ Successfully deployed ${{ steps.get_version.outputs.VERSION }} to production"
      
      - name: Notify deployment failure
        if: failure()
        run: |
          echo "✗ Deployment failed for ${{ steps.get_version.outputs.VERSION }}"

  deploy-development:
    name: Deploy to Development
    runs-on: ubuntu-latest
    needs: [test-backend, test-frontend]
    if: github.ref == 'refs/heads/develop'
    
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEV_DEPLOY_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.DEV_DEPLOY_HOST }} >> ~/.ssh/known_hosts
      
      - name: Deploy to development
        env:
          DEPLOY_HOST: ${{ secrets.DEV_DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEV_DEPLOY_USER }}
          DEPLOY_PATH: ${{ secrets.DEV_DEPLOY_PATH }}
        run: |
          ssh -i ~/.ssh/deploy_key $DEPLOY_USER@$DEPLOY_HOST << 'EOF'
            set -e
            cd $DEPLOY_PATH
            
            # Pull latest develop branch
            git pull origin develop
            
            # Backend
            cd backend
            source .venv/bin/activate
            pip install -q -r requirements.txt
            python manage_migrations.py upgrade
            sudo systemctl restart recipes-backend || flask run --host=0.0.0.0 &
            
            # Frontend
            cd ../frontend
            npm ci --silent
            npm run build
            
            echo "✓ Development deployment successful"
          EOF
